### ISSUE TITLE
某些系统会一直不能替换文件

### ISSUE THREAD

**Issue by FQrabbit** [FunctionClub/LocaleCN#1]
> /bin/bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)

会一直报错↑

出现问题机子（阿里云国内ubuntu14.04）

解决方法：

重新安装中文语言包↓

执行下面↓指令
`sudo apt-get -y install language-pack-zh-hans`

有些已经是root的用户可以直接执行
`apt-get -y install language-pack-zh-hans`

再执行locale命令设置当前locale环境

`locale`

希望帮到有需要的人

**Comment by ghost** [comment]
很棒~
我有空加上去，谢谢提醒。
